import { SignInData, Status } from '~src/@types';

export interface User {
  rol: string;
  estado: boolean;
  google: boolean;
  nombre: string;
  correo: string;
  uid: string;
}

export interface AuthState {
  errorMessage: string | null;
  status: Status;
  token: string | null;
  user: User | null;
}
export interface SignInResponse {
  usuario: User;
  token: string;
}
export interface RegisterData extends SignInData {
  nombre: string;
  rol: 'ADMIN_ROLE' | 'USER_ROLE';
}

// Generated by https://quicktype.io
export interface ProductsResponse {
  total: number;
  productos: Producto[];
}

export interface Producto {
  precio: number;
  _id: string;
  nombre: string;
  categoria: Categoria;
  usuario: Categoria;
  img?: string;
}

export interface Categoria {
  _id: string;
  nombre: string;
}
